filter:
  excluded_paths:
    - 'vendor/*'
    - '.github/*'
    - 'examples/*'
    - 'php-tests/*'
  paths:
    - 'php-src/*'

build:
  environment:
    php:
      version: '7.4'
    variables:
#      SKIP_DB_TESTS: 1
      KW_PEDIGREE_DB_HOST: '127.0.0.1'
      KW_PEDIGREE_DB_USER: 'root'
      KW_PEDIGREE_DB_PASS: ''
      KW_PEDIGREE_DB_NAME: 'scrutinizer_run'

  services:
    mysql: 8.0
  dependencies:
    before:
      - wget -O composer.phar https://getcomposer.org/composer.phar
      - chmod +x composer.phar
      - ./composer.phar install
  project_setup:
    before:
      - sudo service start mysql || true
      - mysql -e "CREATE DATABASE scrutinizer_run"
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
      services:
        mysql: 8.0
    coverage:
      tests:
        override:
          - command: XDEBUG_MODE=coverage ./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover php-tests/data/clover.xml
            coverage:
              file:  php-tests/data/clover.xml
              format: php-clover
      services:
        mysql: 8.0

coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
      ternary_operator:
        in_short_version: false
      other:
        after_type_cast: true
